default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: default
      threads: <%= ENV.fetch("DEFAULT_JOB_THREADS", 3) %>
      processes: <%= ENV.fetch("DEFAULT_JOB_CONCURRENCY") { ENV.fetch("JOB_CONCURRENCY", 1) } %>
      polling_interval: 0.1
    - queues: receipt_analysis
      threads: <%= ENV.fetch("RECEIPT_ANALYSIS_THREADS", 1) %>
      processes: <%= ENV.fetch("RECEIPT_ANALYSIS_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
