class ReceiptAnalysisPipeline
  module Config
    OCR_ENABLED_ENV_KEY = "RECEIPT_OCR_ENABLED"
    AI_ENABLED_ENV_KEY = "RECEIPT_AI_ENABLED"
    SUPPORTED_RECEIPT_COUNTRY_CODES = %w[JPN].freeze
    UNREADABLE_CONFIDENCE_THRESHOLD = 0.3
    REVIEW_NEEDED_CONFIDENCE_THRESHOLD = 0.6
  end
end
